export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const LOGOUT = "LOGOUT";

export const LOAD_ALL_TASKS_START = "LOAD_ALL_TASKS_START";
export const LOAD_ALL_TASKS_SUCCESS = "LOAD_ALL_TASKS_SUCCESS";
export const LOAD_ALL_TASKS_FAIL = "LOAD_ALL_TASKS_FAIL";

export const CREATE_TASK_START = "CREATE_TASK_START";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";

export const DELETE_TASK_START = "DELETE_TASK_START";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const EDIT_TASK_START = "EDIT_TASK_START";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_FAIL = "EDIT_TASK_FAIL";

export const EDIT_USER_START = "EDIT_USER_START";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const DELETE_MULTIPLE_TASKS_START = "DELETE_MULTIPLE_TASKS_START";
export const DELETE_MULTIPLE_TASKS_SUCCESS = "DELETE_MULTIPLE_TASKS_SUCCESS";
export const DELETE_MULTIPLE_TASKS_FAIL = "DELETE_MULTIPLE_TASKS_FAIL";

export const UPDATE_ACTIVE_MULTIPLE_TASKS_START =
  "UPDATE_ACTIVE_MULTIPLE_TASKS_START";
export const UPDATE_ACTIVE_MULTIPLE_TASKS_SUCCESS =
  "UPDATE_ACTIVE_MULTIPLE_TASKS_SUCCESS";
export const UPDATE_ACTIVE_MULTIPLE_TASKS_FAIL =
  "UPDATE_ACTIVE_MULTIPLE_TASKS_FAIL";

export const CHANGE_TASKS_ACTIVE_TAB = "CHANGE_TASKS_ACTIVE_TAB";

export const ADD_SELECTED_ACTIVE_TASK_IDS_TO_CACHE =
  "ADD_SELECTED_ACTIVE_TASK_IDS_TO_CACHE";
export const ADD_SELECTED_FINISHED_TASK_IDS_TO_CACHE =
  "ADD_SELECTED_FINISHED_TASK_IDS_TO_CACHE";

export const CHANGE_ACTIVE_TABLE_SORT = "CHANGE_ACTIVE_TABLE_SORT";
export const CHANGE_FINISHED_TABLE_SORT = "CHANGE_FINISHED_TABLE_SORT";
